2025-05-05 14:59:41,820 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..cases'. (208) (SQLExecDirectW)")
[SQL: SELECT
    (SELECT TOP 1 WITH TIES staff_1 FROM [Needles]..cases WHERE staff_1 <> '' GROUP BY staff_1 ORDER BY COUNT(*) DESC) AS staff_1,
    (SELECT TOP 1 WITH TIES staff_2 FROM [Needles]..cases WHERE staff_2 <> '' GROUP BY staff_2 ORDER BY COUNT(*) DESC) AS staff_2,
    (SELECT TOP 1 WITH TIES staff_3 FROM [Needles]..cases WHERE staff_3 <> '' GROUP BY staff_3 ORDER BY COUNT(*) DESC) AS staff_3,
    (SELECT TOP 1 WITH TIES staff_4 FROM [Needles]..cases WHERE staff_4 <> '' GROUP BY staff_4 ORDER BY COUNT(*) DESC) AS staff_4,
    (SELECT TOP 1 WITH TIES staff_5 FROM [Needles]..cases WHERE staff_5 <> '' GROUP BY staff_5 ORDER BY COUNT(*) DESC) AS staff_5,
    (SELECT TOP 1 WITH TIES staff_6 FROM [Needles]..cases WHERE staff_6 <> '' GROUP BY staff_6 ORDER BY COUNT(*) DESC) AS staff_6,
    (SELECT TOP 1 WITH TIES staff_7 FROM [Needles]..cases WHERE staff_7 <> '' GROUP BY staff_7 ORDER BY COUNT(*) DESC) AS staff_7,
    (SELECT TOP 1 WITH TIES staff_8 FROM [Needles]..cases WHERE staff_8 <> '' GROUP BY staff_8 ORDER BY COUNT(*) DESC) AS staff_8,
    (SELECT TOP 1 WITH TIES staff_9 FROM [Needles]..cases WHERE staff_9 <> '' GROUP BY staff_9 ORDER BY COUNT(*) DESC) AS staff_9,
    (SELECT TOP 1 WITH TIES staff_10 FROM [Needles]..cases WHERE staff_10 <> '' GROUP BY staff_10 ORDER BY COUNT(*) DESC) AS staff_10;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 14:59:41,823 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Case Staff.sql
2025-05-05 14:59:41,834 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..matter'. (208) (SQLExecDirectW)")
[SQL: SELECT
    m.matcode AS case_type,
    m.header,
    m.description,
    m.active,
    c.[count] as case_count,
    CASE WHEN show_value_tab = 'Y' THEN m.value_tab_title ELSE 'N/A' END AS Value_Tab,
    CASE WHEN show_insurance_tab = 'Y' THEN m.insurance_tab_title ELSE 'N/A' END AS Insurance_Tab,
    CASE WHEN show_negotiation_tab = 'Y' THEN m.negotiation_tab_title ELSE 'N/A' END AS Negotiation_Tab,
    CASE WHEN show_counsel_tab = 'Y' THEN m.counsel_tab_title ELSE 'N/A' END AS Counsel_Tab,
    CASE WHEN show_police_tab = 'Y' THEN m.police_tab_title ELSE 'N/A' END AS Police_Tab,
    CASE WHEN show_document_tab = 'Y' THEN m.documents_tab_title ELSE 'N/A' END AS Documents_Tab,
    CASE WHEN show_status_tab = 'Y' THEN m.status_title ELSE 'N/A' END AS Status_Tab,
    CASE WHEN show_crm_tab = 'Y' THEN m.crm_title ELSE 'N/A' END AS CRM_Tab,
    CASE WHEN show_time_tab = 'Y' then m.time_tab_title ELSE 'N/A' END AS Time_Tab,
	CASE WHEN show_user_tab = 'Y' THEN tab_title ELSE 'N/A' END AS user_tab_1,
    CASE WHEN show_user_tab2 = 'Y' THEN tab2_title ELSE 'N/A' END AS user_tab_2,
    CASE WHEN show_user_tab3 = 'Y' THEN tab3_title  ELSE 'N/A' END AS user_tab_3,
    CASE WHEN show_user_tab4 = 'Y' THEN tab4_title  ELSE 'N/A' END AS user_tab_4,
    CASE WHEN show_user_tab5 = 'Y' THEN tab5_title  ELSE 'N/A' END AS user_tab_5,
    CASE WHEN show_user_tab6 = 'Y' THEN tab6_title  ELSE 'N/A' END AS user_tab_6,
    CASE WHEN show_user_tab7 = 'Y' THEN tab7_title  ELSE 'N/A' END AS user_tab_7,
    CASE WHEN show_user_tab8 = 'Y' THEN tab8_title  ELSE 'N/A' END AS user_tab_8,
    CASE WHEN show_user_tab9 = 'Y' THEN tab9_title  ELSE 'N/A' END AS user_tab_9,
    CASE WHEN show_user_tab10 = 'Y' THEN tab10_title else 'N/A' END AS user_tab_10
FROM [Needles]..matter m
INNER JOIN (
    SELECT
        ci.matcode,
        COUNT(*) AS [count]
    FROM [Needles]..cases_indexed ci
    GROUP BY ci.matcode
) c
    ON m.matcode = c.matcode
ORDER BY m.matcode;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 14:59:41,835 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Case Types.sql
2025-05-05 14:59:42,263 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..party_Indexed'. (208) (SQLExecDirectW)")
[SQL: SELECT
	[role]
   ,COUNT(*) AS Count
FROM [Needles]..party_Indexed
WHERE ISNULL([role], '') <> ''
GROUP BY [role]]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 14:59:42,264 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Party Roles.sql
2025-05-05 14:59:42,292 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 14:59:42,351 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 14:59:42,378 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 14:59:42,390 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 14:59:42,426 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..value_code'. (208) (SQLExecDirectW)")
[SQL: SELECT
	code,
	description,
	c_d,
	dtf
FROM [Needles]..value_code]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 14:59:42,426 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Value Codes.sql
2025-05-05 14:59:43,320 - INFO - map.py - save_to_excel - 56 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 14:59:43,322 - INFO - map.py - main - 123 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:00:35,555 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..cases'. (208) (SQLExecDirectW)")
[SQL: SELECT
    (SELECT TOP 1 WITH TIES staff_1 FROM [Needles]..cases WHERE staff_1 <> '' GROUP BY staff_1 ORDER BY COUNT(*) DESC) AS staff_1,
    (SELECT TOP 1 WITH TIES staff_2 FROM [Needles]..cases WHERE staff_2 <> '' GROUP BY staff_2 ORDER BY COUNT(*) DESC) AS staff_2,
    (SELECT TOP 1 WITH TIES staff_3 FROM [Needles]..cases WHERE staff_3 <> '' GROUP BY staff_3 ORDER BY COUNT(*) DESC) AS staff_3,
    (SELECT TOP 1 WITH TIES staff_4 FROM [Needles]..cases WHERE staff_4 <> '' GROUP BY staff_4 ORDER BY COUNT(*) DESC) AS staff_4,
    (SELECT TOP 1 WITH TIES staff_5 FROM [Needles]..cases WHERE staff_5 <> '' GROUP BY staff_5 ORDER BY COUNT(*) DESC) AS staff_5,
    (SELECT TOP 1 WITH TIES staff_6 FROM [Needles]..cases WHERE staff_6 <> '' GROUP BY staff_6 ORDER BY COUNT(*) DESC) AS staff_6,
    (SELECT TOP 1 WITH TIES staff_7 FROM [Needles]..cases WHERE staff_7 <> '' GROUP BY staff_7 ORDER BY COUNT(*) DESC) AS staff_7,
    (SELECT TOP 1 WITH TIES staff_8 FROM [Needles]..cases WHERE staff_8 <> '' GROUP BY staff_8 ORDER BY COUNT(*) DESC) AS staff_8,
    (SELECT TOP 1 WITH TIES staff_9 FROM [Needles]..cases WHERE staff_9 <> '' GROUP BY staff_9 ORDER BY COUNT(*) DESC) AS staff_9,
    (SELECT TOP 1 WITH TIES staff_10 FROM [Needles]..cases WHERE staff_10 <> '' GROUP BY staff_10 ORDER BY COUNT(*) DESC) AS staff_10;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:00:35,557 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Case Staff.sql
2025-05-05 15:00:35,560 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..matter'. (208) (SQLExecDirectW)")
[SQL: SELECT
    m.matcode AS case_type,
    m.header,
    m.description,
    m.active,
    c.[count] as case_count,
    CASE WHEN show_value_tab = 'Y' THEN m.value_tab_title ELSE 'N/A' END AS Value_Tab,
    CASE WHEN show_insurance_tab = 'Y' THEN m.insurance_tab_title ELSE 'N/A' END AS Insurance_Tab,
    CASE WHEN show_negotiation_tab = 'Y' THEN m.negotiation_tab_title ELSE 'N/A' END AS Negotiation_Tab,
    CASE WHEN show_counsel_tab = 'Y' THEN m.counsel_tab_title ELSE 'N/A' END AS Counsel_Tab,
    CASE WHEN show_police_tab = 'Y' THEN m.police_tab_title ELSE 'N/A' END AS Police_Tab,
    CASE WHEN show_document_tab = 'Y' THEN m.documents_tab_title ELSE 'N/A' END AS Documents_Tab,
    CASE WHEN show_status_tab = 'Y' THEN m.status_title ELSE 'N/A' END AS Status_Tab,
    CASE WHEN show_crm_tab = 'Y' THEN m.crm_title ELSE 'N/A' END AS CRM_Tab,
    CASE WHEN show_time_tab = 'Y' then m.time_tab_title ELSE 'N/A' END AS Time_Tab,
	CASE WHEN show_user_tab = 'Y' THEN tab_title ELSE 'N/A' END AS user_tab_1,
    CASE WHEN show_user_tab2 = 'Y' THEN tab2_title ELSE 'N/A' END AS user_tab_2,
    CASE WHEN show_user_tab3 = 'Y' THEN tab3_title  ELSE 'N/A' END AS user_tab_3,
    CASE WHEN show_user_tab4 = 'Y' THEN tab4_title  ELSE 'N/A' END AS user_tab_4,
    CASE WHEN show_user_tab5 = 'Y' THEN tab5_title  ELSE 'N/A' END AS user_tab_5,
    CASE WHEN show_user_tab6 = 'Y' THEN tab6_title  ELSE 'N/A' END AS user_tab_6,
    CASE WHEN show_user_tab7 = 'Y' THEN tab7_title  ELSE 'N/A' END AS user_tab_7,
    CASE WHEN show_user_tab8 = 'Y' THEN tab8_title  ELSE 'N/A' END AS user_tab_8,
    CASE WHEN show_user_tab9 = 'Y' THEN tab9_title  ELSE 'N/A' END AS user_tab_9,
    CASE WHEN show_user_tab10 = 'Y' THEN tab10_title else 'N/A' END AS user_tab_10
FROM [Needles]..matter m
INNER JOIN (
    SELECT
        ci.matcode,
        COUNT(*) AS [count]
    FROM [Needles]..cases_indexed ci
    GROUP BY ci.matcode
) c
    ON m.matcode = c.matcode
ORDER BY m.matcode;]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:00:35,560 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Case Types.sql
2025-05-05 15:00:35,565 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..party_Indexed'. (208) (SQLExecDirectW)")
[SQL: SELECT
	[role]
   ,COUNT(*) AS Count
FROM [Needles]..party_Indexed
WHERE ISNULL([role], '') <> ''
GROUP BY [role]]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:00:35,566 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Party Roles.sql
2025-05-05 15:00:35,572 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:00:35,599 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:00:35,611 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:00:35,614 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:00:35,631 - ERROR - map.py - execute_query - 42 - Error executing query: (pyodbc.ProgrammingError) ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'Needles..value_code'. (208) (SQLExecDirectW)")
[SQL: SELECT
	code,
	description,
	c_d,
	dtf
FROM [Needles]..value_code]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:00:35,632 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: Value Codes.sql
2025-05-05 15:00:36,035 - INFO - map.py - save_to_excel - 56 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:00:36,037 - INFO - map.py - main - 123 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:02:07,757 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:02:07,803 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:02:07,819 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:02:07,823 - WARNING - map.py - process_sql_files - 80 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:02:08,276 - INFO - map.py - save_to_excel - 56 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:02:08,278 - INFO - map.py - main - 123 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:14:06,153 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_case_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,156 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_case_data.sql
2025-05-05 15:14:06,159 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_counsel_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,160 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:14:06,162 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_insurance_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,163 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_insurance_data.sql
2025-05-05 15:14:06,164 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_party_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,165 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_party_data.sql
2025-05-05 15:14:06,168 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab10_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,168 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab10_data.sql
2025-05-05 15:14:06,171 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab2_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,171 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab2_data.sql
2025-05-05 15:14:06,173 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab3_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,174 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab3_data.sql
2025-05-05 15:14:06,176 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab4_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,176 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:14:06,179 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab5_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,179 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab5_data.sql
2025-05-05 15:14:06,181 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab6_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,182 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab6_data.sql
2025-05-05 15:14:06,185 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab7_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,185 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:14:06,189 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab8_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,189 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:14:06,193 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab9_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,193 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab9_data.sql
2025-05-05 15:14:06,196 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,197 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab_data.sql
2025-05-05 15:14:06,200 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_value_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:14:06,201 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_value_data.sql
2025-05-05 15:14:06,426 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:14:06,428 - INFO - map.py - map - 128 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:15:12,477 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:15:12,499 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_party_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,500 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_party_data.sql
2025-05-05 15:15:12,502 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab10_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,503 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab10_data.sql
2025-05-05 15:15:12,506 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab2_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,506 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab2_data.sql
2025-05-05 15:15:12,508 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab3_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,508 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab3_data.sql
2025-05-05 15:15:12,510 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab4_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,511 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:15:12,513 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab5_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,513 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab5_data.sql
2025-05-05 15:15:12,516 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab6_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,517 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab6_data.sql
2025-05-05 15:15:12,518 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab7_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,519 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:15:12,523 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab8_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,524 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:15:12,527 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab9_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,528 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab9_data.sql
2025-05-05 15:15:12,530 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_tab_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,530 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab_data.sql
2025-05-05 15:15:12,533 - ERROR - map.py - execute_query - 43 - Error executing query: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'table'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'record_count'. (207)")
[SQL: select
	cfu.[table],
	cfu.[column_name],
	[field_title],
	[field_type],
	[field_len],
	[caseid] as case_link,
	[record_count],
	CFSD.field_value as [Sample Data]
from CustomFieldUsage CFU
left join CustomFieldSampleData CFSD
	on CFU.column_name = CFSD.column_name
		and CFU.tablename = CFSD.tablename
where
	CFU.tablename = 'user_value_data'
order by CFU.tablename, CFU.field_num]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-05-05 15:15:12,534 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_value_data.sql
2025-05-05 15:15:12,789 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:15:12,791 - INFO - map.py - map - 128 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:16:48,379 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:16:48,443 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:16:48,464 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:16:48,475 - WARNING - map.py - process_sql_files - 81 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:16:48,890 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:16:48,893 - INFO - map.py - map - 128 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:20:13,300 - ERROR - map.py - process_sql_files - 84 - Failed to read SQL file Case Staff.sql: cannot access local variable 'df' where it is not associated with a value
2025-05-05 15:20:13,301 - ERROR - map.py - process_sql_files - 84 - Failed to read SQL file Case Types.sql: cannot access local variable 'df' where it is not associated with a value
2025-05-05 15:20:13,301 - ERROR - map.py - process_sql_files - 84 - Failed to read SQL file Intake.sql: cannot access local variable 'df' where it is not associated with a value
2025-05-05 15:20:13,302 - ERROR - map.py - process_sql_files - 84 - Failed to read SQL file Party Roles.sql: cannot access local variable 'df' where it is not associated with a value
2025-05-05 15:20:13,370 - WARNING - map.py - process_sql_files - 82 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:20:13,401 - WARNING - map.py - process_sql_files - 82 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:20:13,416 - WARNING - map.py - process_sql_files - 82 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:20:13,419 - WARNING - map.py - process_sql_files - 82 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:20:13,781 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:20:13,787 - INFO - map.py - map - 129 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:20:56,626 - WARNING - map.py - process_sql_files - 84 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:20:56,662 - WARNING - map.py - process_sql_files - 84 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:20:56,672 - WARNING - map.py - process_sql_files - 84 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:20:56,675 - WARNING - map.py - process_sql_files - 84 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:20:57,058 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:20:57,064 - INFO - map.py - map - 131 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:32:21,273 - WARNING - map.py - process_sql_files - 107 - Empty DataFrame for SQL file: user_counsel_data.sql
2025-05-05 15:32:21,315 - WARNING - map.py - process_sql_files - 107 - Empty DataFrame for SQL file: user_tab4_data.sql
2025-05-05 15:32:21,333 - WARNING - map.py - process_sql_files - 107 - Empty DataFrame for SQL file: user_tab7_data.sql
2025-05-05 15:32:21,341 - WARNING - map.py - process_sql_files - 107 - Empty DataFrame for SQL file: user_tab8_data.sql
2025-05-05 15:32:21,719 - INFO - map.py - save_to_excel - 57 - Excel file saved successfully to: D:\john-salazar\john-salazar Data Mapping.xlsx
2025-05-05 15:32:21,724 - INFO - map.py - map - 154 - Saved results to D:\john-salazar\john-salazar Data Mapping.xlsx
